services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kulan-website
    restart: always
    ports:
      - "3005:3000" # Используем уникальный порт, чтобы не конфликтовать с другими сайтами
    environment:
      - DATABASE_URL=file:./data/prod.db
      - SESSION_SECRET=change-me-at-least-32-chars-long
      - NEXT_PUBLIC_SITE_URL=https://adkulan.shop
    volumes:
      - ./prisma/data:/app/prisma/data
