services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kulan-website
    restart: always
    ports:
      - "3005:3000" # Используем уникальный порт, чтобы не конфликтовать с другими сайтами
    environment:
      - DATABASE_URL=file:/app/data/prod.db
      - SESSION_SECRET=change-this-to-a-very-secure-random-string
      - NEXT_PUBLIC_SITE_URL=https://adkulan.shop
      - JWT_SECRET=your_super_secure_jwt_secret_key_here
    volumes:
      - ./data:/app/data
      - ./uploads:/app/public/uploads
